spring:
  application:
    name: AccountManagement
  profiles:
    active: dev  # default profile set to 'dev'. Change to 'uat' or 'prod' as needed.

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

####################   PUBLIC ENDPOINTS CONFIG #####################
app:
  public-endpoints: /unsecure,/h2-console

# Swagger UI ==> http://localhost:9090/swagger-ui/index.html

####### USER CREDENTIALS #########
# Customer ==> tic293/tic293
# Admin ==>  admin/admin